#!/bin/sh

NEWLINE="
"

questionar(){
  printf "$1"
  read resposta
  [ "$2" = "$resposta" ]
  return $?
}

genconf(){
  TARGET="$1"
  TARGET_PATH="$(echo $TARGET | sed 's/[[:alnum:]\ ._]*$//')"

  CONFIG_OUTPUT="$TARGET_PATH""index.md:$NEWLINE"
  CONFIG_OUTPUT="$CONFIG_OUTPUT""> ./Makepage $TARGET_PATH""index.md"
  SED_ARGS=""

  questionar "Barra de navegação? [s/n] " "s"
  if [ $? -ne 0 ]
  then
    SED_ARGS="$SED_ARGS \\""$NEWLINE"
    SED_ARGS="$SED_ARGS""> -e '/nav/d'"
  else
    questionar "Setas de navegação? [s/n] " "s"
    if [ $? -ne 0 ]
    then
      SED_ARGS="$SED_ARGS \\""$NEWLINE"
      SED_ARGS="$SED_ARGS""> -e '/nav arrow/d'"
    fi
  fi

  questionar "Última modificação? [s/n] " "s"
  if [ $? -ne 0 ]
  then
    SED_ARGS="$SED_ARGS \\""$NEWLINE"
    SED_ARGS="$SED_ARGS""> -e '/last-modified/d'"
  fi

  questionar "Estilos para imagens? [s/n] " "s"
  if [ $? -ne 0 ]
  then
    SED_ARGS="$SED_ARGS"" \\""$NEWLINE"
    SED_ARGS="$SED_ARGS""> -e '/imagens\.css/d'"
  fi

  questionar "Estilos para tabelas? [s/n] " "s"
  if [ $? -ne 0 ]
  then
    SED_ARGS="$SED_ARGS"" \\""$NEWLINE"
    SED_ARGS="$SED_ARGS""> -e '/tabela\.css/d'"
  fi

  questionar "Agregador RSS? [s/n] " "s"
  if [ $? -ne 0 ]
  then
    SED_ARGS="$SED_ARGS"" \\""$NEWLINE"
    SED_ARGS="$SED_ARGS""> -e '/feed.xml/d'"
  fi

  if [ "$SED_ARGS" ]
  then
    CONFIG_OUTPUT="$CONFIG_OUTPUT""$NEWLINE"
    CONFIG_OUTPUT="$CONFIG_OUTPUT""> sed -i ""$TARGET_PATH""index.html"
    CONFIG_OUTPUT="$CONFIG_OUTPUT""$SED_ARGS"
  fi

  echo "" > genconf_output.txt
  echo "$CONFIG_OUTPUT" >> genconf_output.txt
}

main(){
  for MDFILE in $(./Makescan)
  do
    MDFILE=$(echo "$MDFILE" | cut -c 3-)
    if ! grep "$MDFILE" Makefile > /dev/null
    then
      questionar "./$MDFILE não está incluso no Makefile. Quer configurá-lo? [s/n] " "s"
      if [ $? -ne 0 ]
      then
        echo "Ignorando..."
      else
        genconf "$MDFILE"
        cat genconf_output.txt >> Makefile
        rm genconf_output.txt
        echo "$MDFILE configurado com sucesso."
      fi
    fi
  done
}

main $@
